.editorconfig
Cargo.toml
src/lib.rs
src/libraryfolders.rs
src/steamapp.rs
src/steamapps.rs
src/tests.rs

This switches just the `libraryfolders.vdf` parsing to use [`keyvalues-parser`](https://docs.rs/keyvalues-parser/latest/keyvalues_parser/) which gets things into a working state for now (all the tests are passing for me :partying_face:). I was not able to test on windows though since anti-virus seemed to be silently killing the test program I cross-compiled
I do have plans to swap out the app manifest parsing as well since it seems a bit silly to use two separate parsers, and there's no telling what other issues the old parser may have on random app manifest files
_Side note: The `.editorconfig` change was because the editor config used `crlf` while all the other files used just `lf` so `.editorconfig` seemed like the smaller change and `lf` is more common AFAIK_

Fix `libraryfolders.vdf` parsing

---

.editorconfig
Cargo.toml
src/lib.rs
src/steamapps.rs

Coming in just a hair too late for the version bump from the looks of it
This change just removed some deps. `anyhow` wasn't used, and `regex` with `lazy_static` was just for extracting out the app id from the manifest file name which is easy enough to do with some manual string manipulation

Deps cleanup

---

src/lib.rs
src/libraryfolders.rs
src/steamapp.rs
src/steamapps.rs
src/tests.rs

I normally have format-on-save on with my editor, so it's easier to send in an initial PR for formatting before followup PRs (easy enough to verify if you just run `cargo fmt` on `master` locally)
I'm finally getting settled in from moving, so I've got time to start working through #7 :tada:

Format with `cargo fmt`

---

src/lib.rs

Quick and easy PR to add support for other Steam install paths. Flatpak still take precedence over native, so dirs that persist after uninstallation may cause problems (issue #17).
I can also add Snap support if needed, however I would rather not obstruct the work done in PR #30.

Add additional Steam search paths for Linux

---

.github/workflows/ci.yml
.github/workflows/publish.yml

This resolves the deprecation notice from GH actions runs

Bump `actions/checkout` to v3

---

src/lib.rs

Steam exists on snap! (unsure if in an official capacity, but its packaged by Canonical).
I put the code after the generic `$HOME/.steam/steam` check, because in the small testing I did Proton was completely unusable so any other released should be preferred.

Add snap support for linux

---

Cargo.toml
src/__test_helpers.rs
src/error.rs
src/lib.rs
src/tests.rs
tests/assets/appmanifest_4000.acf
tests/assets/libraryfolder.vdf

This change refactors how tests are run to setup dummy steam installations (well only the bits we need) that each test can run against in isolation. This is exciting for a number of reasons and it opens the door to a lot more testing related changes

Switch tests to run in isolated dummy steam installations

---

src/lib.rs
src/test_helpers.rs
src/tests.rs

On further thought the juice doesn't seem worth the squeeze. The bulk of the complexity was providing helpers that would work with integration tests. We can just stick to unit tests and doc tests instead. It's simple enough to treat unit tests as integration tests anyways

Drastically simplify test helpers

---

.github/workflows/ci.yml
src/lib.rs

Now that tests are switched to use isolated dummy steam installations we can actually test stuff in CI :tada:

Run `cargo test` in CI

---

src/lib.rs

There were some clippy lint violations hiding behind various `cfg`s. This should fix all of those

Fix clippy lints on more platforms

---

.github/workflows/ci.yml

This switches CI to run on all the platforms that we have `cfg`s for along with checking against both the stable and beta toolchains to try and catch issues earlier when possible

Run CI on more platforms/channels

---

src/error.rs
src/lib.rs
src/libraryfolders.rs
src/shortcut.rs
src/steamapp.rs

The commits should be pretty descriptive
This polishes up some remaining rough edges with the existing error handling

Error cleanup

---

src/lib.rs
src/library.rs

Relevant context https://github.com/WilliamVenner/steamlocate-rs/issues/48#issuecomment-1833309059
This exposes `Library::from_dir()` which allows for constructing a library from an arbitrary directory like the new `InstallDir::from_steam_dir()` along with adding a way to get the full listing of library paths from an `InstallDir`. This makes `InstallDir::libraries` a trivial combination of the two :)

Expose `Library::from_dir()` and `InstallDir::library_paths()`

---

.cargo/config.toml
Cargo.toml
examples/appmanifest.rs
src/app.rs
src/lib.rs
src/library.rs
src/shortcut.rs
src/snapshots/steamlocate__app__tests__more_sanity.snap
src/snapshots/steamlocate__app__tests__sanity.snap
src/tests/helpers.rs
src/tests/legacy.rs
src/tests/mod.rs
src/tests/temp.rs

Still got a lot more to do, but it's a start

Docs overhaul

---

Cargo.toml
README.md
examples/shortcuts.rs
src/lib.rs
src/shortcut.rs
src/tests/helpers.rs

This just finishes up the remaining bit of polish I wanted to get through before publishing a beta

Prepare the v2.0 beta release

---

.cargo/config.toml
Cargo.toml
src/tests/legacy.rs
src/tests/temp.rs

The beta push failed to build docs because of a missing `tempfile` dependency. I tried replicating the failure, but it seems like docs.rs just ignores that extra `cfg(steamlocate_doctest)` dependency
I got tired of dealing with the headache since everything seems to work fine locally. We don't use much from `tempfile`, so it's easy enough to provide our own

Remove need to use `tempfile`

---

src/app.rs
src/snapshots/steamlocate__app__tests__minimal.snap

Resolves #58
It makes sense, but I wasn't really thinking about how the custom deserialization function means that it's not appropriate to infer `Option`'s default

Make `app.last_updated` actually optional

---

.github/workflows/ci.yml
Cargo.toml
src/error.rs
src/tests/mod.rs
src/tests/wasm.rs

For a very brief time we supported WASM until I broke it almost immediately after. This fixes WASM support and starts testing against WASM in CI, so we get a heads up before things break again

Fix WASM support

---

.github/dependabot.yml

This adds a dependabot flow to handle updating our github actions actions since it's very easy to accidentally let those get out of date
This should also eventually fix the current CI warnings about outdated actions

Add a basic dependabot flow

---

Cargo.toml
src/__private_tests/helpers.rs

Our MSRV is already past the 2021 edition, so no reason to stay on the 2018 edition

refactor: Update to 2021 edition

---

.editorconfig
src/shortcut.rs

And another commit to get rid of a blanket `.editorconfig` definition that kept messing up my formatting :smiling_imp:

refactor: Swtich `Shortcut::steam_id` from a field to a method

---

src/__private_tests/mod.rs
tests/legacy.rs
tests/tests.rs
tests/wasm.rs

If they don't rely on anything internal then there's no point in them being unit tests

Make tests into integration tests where possible

---

src/locate.rs

Hello!
I found this project and noticed that it doesn't try to check one specific path that i needed for another project (ALVR) and decided to add it.
This is primarily (probably) used for Linux Mint, but i assume Debian itself also gonna have similar path.

feat: add debian-installation path to unique steam paths

---

Cargo.lock
Cargo.toml
src/__private_tests/helpers.rs
src/app.rs
src/config.rs

The clean build time for crates largely depends on the critical chain of crate dependencies, i.e. the one that takes longest to compile.
A frequent contender for this critical chain is `syn -> serde -> serde_derive -> ...`.
By removing the `serde_derive` feature, we cut that to
```
serde -> steamlocate
syn -> serde_derive -> steamlocate
```
which **can** reduce the build time depending on the other crates in the graph.
**Before**
**After**
---
So while this comes with a small maintenance burden (you get different imports, and should take care not to import `serde_derive::Deserialize` and `serde::Deserialize`) I hope it's worth it, as these small things can add up :)

feat: depend on `serde_derive` and `serde` separately for compile time improvement
